data:
  dataset: msn
  path: /mnt/lustre/geiger/gwb746/datasets/msn_hard/
  num_points: 2560
  kwargs:
    downsample: 0
    num_input_views: 5
    num_target_views: 5

model:
  model_type: srt
  args:
    encoder: isrt
    decoder: isrt
    encoder_kwargs:
      pos_start_octave: -5
      dropout: 0.01
      heads: 12
      attn_args: 
        method:
          name: ''
          args: {}

    decoder_kwargs:
      z_dim: 768
      pos_start_octave: -5
      dropout: 0.01
      heads: 12
      attn_args: 
        method:
          name: ''
          args: {}


training:
  mixed_prec: True
  num_workers: 1
  batch_size: 64
  model_selection_metric: psnr
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 1000
  backup_every: 25000
  max_it: 4000000
  decay_it: 2000000
  lr_warmup: 10000
